// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjcWILdMcdV4u0fzOHvrO-kzr-16PzDxI',
    appId: '1:842703409113:web:ade0f821e37458ee7813c8',
    messagingSenderId: '842703409113',
    projectId: 'flutter-base-app-b41d1',
    authDomain: 'flutter-base-app-b41d1.firebaseapp.com',
    storageBucket: 'flutter-base-app-b41d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Jw6KDr-Zvt5dMFS5KxrEYhHfGixVUqY',
    appId: '1:842703409113:android:a641f8eae977ff447813c8',
    messagingSenderId: '842703409113',
    projectId: 'flutter-base-app-b41d1',
    storageBucket: 'flutter-base-app-b41d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ooHk7Vqg_SZFan_eI_ZoYZyRpmqR6IQ',
    appId: '1:842703409113:ios:cfcd4fafded46c427813c8',
    messagingSenderId: '842703409113',
    projectId: 'flutter-base-app-b41d1',
    storageBucket: 'flutter-base-app-b41d1.appspot.com',
    iosBundleId: 'com.example.readingApp9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4ooHk7Vqg_SZFan_eI_ZoYZyRpmqR6IQ',
    appId: '1:842703409113:ios:cfcd4fafded46c427813c8',
    messagingSenderId: '842703409113',
    projectId: 'flutter-base-app-b41d1',
    storageBucket: 'flutter-base-app-b41d1.appspot.com',
    iosBundleId: 'com.example.readingApp9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjcWILdMcdV4u0fzOHvrO-kzr-16PzDxI',
    appId: '1:842703409113:web:7438d61f69d4b6fb7813c8',
    messagingSenderId: '842703409113',
    projectId: 'flutter-base-app-b41d1',
    authDomain: 'flutter-base-app-b41d1.firebaseapp.com',
    storageBucket: 'flutter-base-app-b41d1.appspot.com',
  );
}
