// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNCWB7LL9JdH1-MWO8EbklNTTE8ZpY6Z4',
    appId: '1:289292635767:web:bc3e8f7eeef005cf944072',
    messagingSenderId: '289292635767',
    projectId: 'readingapp9',
    authDomain: 'readingapp9.firebaseapp.com',
    storageBucket: 'readingapp9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzk_RvTv4JaqGexhl3lXGNOIAHO3n4tio',
    appId: '1:289292635767:android:bee0445b6362d415944072',
    messagingSenderId: '289292635767',
    projectId: 'readingapp9',
    storageBucket: 'readingapp9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Od-6Ah0EoWfxDqPEfYyaBIqstHZOEco',
    appId: '1:289292635767:ios:b83a377dafe8f8ae944072',
    messagingSenderId: '289292635767',
    projectId: 'readingapp9',
    storageBucket: 'readingapp9.appspot.com',
    iosBundleId: 'com.example.readingApp9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Od-6Ah0EoWfxDqPEfYyaBIqstHZOEco',
    appId: '1:289292635767:ios:b83a377dafe8f8ae944072',
    messagingSenderId: '289292635767',
    projectId: 'readingapp9',
    storageBucket: 'readingapp9.appspot.com',
    iosBundleId: 'com.example.readingApp9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNCWB7LL9JdH1-MWO8EbklNTTE8ZpY6Z4',
    appId: '1:289292635767:web:3e6a10181882b52e944072',
    messagingSenderId: '289292635767',
    projectId: 'readingapp9',
    authDomain: 'readingapp9.firebaseapp.com',
    storageBucket: 'readingapp9.appspot.com',
  );
}
